### ISSUE TITLE
blank page, is it working?

### ISSUE THREAD

**Issue by alfianguide** [kevinaltaf/vanilla-movies#2]
when i search something and didn't find anything, can it show, not found instead of displaying blank page? more likely, is this app working? or this is a joke?

**Comment by kevinaltaf** [comment]
@alfianguide 

This website uses the omdb API for free and has a limit of 1000 hits per day and make sure you are connected to the internet, maybe your connection is busy 😊

**Comment by alfianguide** [comment]
Lol hh that was not what i mean

**Comment by kevinaltaf** [comment]
I forgot to tell that this website uses AJAX so it needs a web server like apache / nginx or you can install the npm live-server package @alfianguide

**Comment by kevinaltaf** [comment]
maybe I'll give the demo using free github hosting

**Comment by alfianguide** [comment]
Noooo, that was not what i mean, you know there's a title, a search box and result section, the result section is blank when the search result provides nothing, it's not the entire page blank, but when it's provides a result then the result section has something to display

**Comment by alfianguide** [comment]
Language barrier

**Comment by kevinaltaf** [comment]
I will try it later
